particlesJS("particles-js",{
	"particles":{
		"number":{
			"value":60,//���̐��l��ύX����Ɗ􉽊w�͗l�̐��������ł���
			"density":{
				"enable":false,
				"value_area":800
			}
		},
		"color":{
			"value":"#ffffff"//�F
		},
		"shape":{
			"type":"polygon",//�`���polygon���w��
			"stroke":{
				"width":0,
			},
	"polygon":{
		"nb_sides":5//���p�`�̊p�̐�
	},
	"image":{
		"width":190,
		"height":100
	}
	},
		"opacity":{
		"value":0.2,
		"random":true,
		"anim":{
			"enable":true,
			"speed":1,
			"opacity_min":0.5,
			"sync":false
		}
		},
		"size":{
			"value":3,
			"random":true,
			"anim":{
				"enable":false,
				"speed":40,
				"size_min":0.1,
				"sync":false
			}
		},
		"line_linked":{
			"enable":true,
			"distance":150,
			"color":"#ffffff",
			"opacity":0.6,
			"width":1
		},
		"move":{
			"enable":true,
			"speed":2,//���̐��l������������Ƃ������ȓ����ɂȂ�
			"direction":"none",//�����w��Ȃ�
			"random":false,//�����̓����_���ɂ��Ȃ�
			"straight":false,//�������Ƃǂ߂Ȃ�
			"out_mode":"bounce",//��ʂ̊O�ɏo��悤�ɕ`��
			"bounce":false,//���˕Ԃ�Ȃ�
			"attract":{
				"enable":false,
				"rotateX":600,
				"rotateY":961.4383117143238
			}
		}
	},
	"interactivity":{
		"detect_on":"canvas",
		"events":{
			"onhover":{
				"enable":false,
				"mode":"repulse"
			},
	"onclick":{
		"enable":false
	},
	"resize":true
		}
	},
	"retina_detect":true
});